version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - run:
          name: Install Python package in a venv
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -e panja
    
workflows:
  main:
    jobs:
      - build
